application:
  local:
    server:
      port: 8080

spring:
  application:
    name: example_maven_springboot_fullstack
  datasource:
    url: jdbc:h2:mem:f1
    username: sa
    password:
    driverClassName: org.h2.Driver
  http:
    converters:
      preferred-json-mapper: gson
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always # default for H2 instances
example-maven-springboot-fullstack:
  rapid-api:
    key: 
